# Generated by Django 6.0.5 on 2026-05-29 02:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('score_obtained', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='quizzes.question')),
            ],
        ),
        migrations.CreateModel(
            name='AttemptAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='attempts.attemptanswer')),
                ('question_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_in', to='quizzes.questionoption')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('total_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz')),
            ],
        ),
    ]
